//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('SupportTickets')
export class SupportTicketsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  relatedTicket: string;

  @Column('integer', { nullable: true })
  relatedUser: number;

  @Column('integer', { nullable: true })
  relatedCustomer: number;

  @Column('text', { nullable: true })
  status: string;

  @Column('date', { nullable: true })
  creationDate: Date;

  @Column('date', { nullable: true })
  resolutionDate: Date;
}
